# Generated by Django 6.1 on 2026-08-19 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobanalysis',
            name='interview_questions',
            field=models.TextField(blank=True, help_text='AI generated role-specific interview questions & answers', null=True),
        ),
        migrations.AddField(
            model_name='jobanalysis',
            name='match_analysis',
            field=models.TextField(blank=True, help_text='AI job match evaluation and gap analysis', null=True),
        ),
        migrations.AddField(
            model_name='jobanalysis',
            name='match_score',
            field=models.IntegerField(blank=True, help_text='AI calculated match score percentage (0-100)', null=True),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(max_length=100),
        ),
    ]
